# Template for Sampling molecules from a trained model

run_type = "sampling"
device = "{device}"

[parameters]
num_smiles = "{sampling_num_smiles}"
unique_molecules = "{sampling_unique_molecules}"
randomize_smiles = "{sampling_randomize_smiles}"

# Dynamic paths
model_file = "{model_file}"
output_file = "{output_file}"
