root_dir: '../../../data'
raw_data_dir: 'raw'
data_dict:
#  expert: 'data_experts1.csv'
#  zhu: 'data_zhu.csv'
#  saad: 'data_saad.csv'
#  expert2: 'data_experts2.csv'
#  expert3: 'data_experts3.csv'
  all: 'data_substrates_june2025_no_outliers.csv'

custom_features: True
custom_features_params:
  dir: 'processed_selected_custom_features'
  translation_table: 'symmetries/symmetry_translation.csv'

expert_substructures: True
expert_substructures_params:
  dir: 'processed_expert_substructures'
  count: False

dft_features: False
dft_features_params:
  dir: 'processed_dft_features'
  functional: 'pbe'
  n_jobs: 8

fingerprints: True
fingerprints_types:
  ecfp: True
  maccs: True
  functional_groups: True
  estate: True
  layered: True
  topological: True
  vsa: True
fingerprints_params:
  ecfp:
    dir: 'fingerprints_ecfp_128'
    kwargs:
        radius: 2
        size: 128
        count: False
  vsa:
    dir: 'fingerprints_vsa'
    kwargs:
        variant: 'EState'
  maccs:
      dir: 'fingerprints_maccs'
      kwargs:
        count: False
  functional_groups:
      dir: 'fingerprints_functional_groups'
      kwargs:
          count: False
  estate:
      dir: 'fingerprints_estate'
      kwargs:
          variant: 'sum'
  layered:
      dir: 'fingerprints_layered_128'
      kwargs:
          size: 128
          linear_paths_only: False
  topological:
      dir: 'fingerprints_topological_128'
      kwargs:
          size: 128
          torsion_atoms: 4
          count: False

additive_groups: False
additive_groups_params:
  dir: 'additive_groups'
  training_set: ['expert', 'expert2', 'zhu', 'saad', 'expert3']
