root_dir: '../../../data'
data_dir: 'processed_dft_features'
save_dir: 'aggregated_dft_features'
data_dict:
  expert: 'data_experts1.csv'
  zhu: 'data_zhu.csv'
  saad: 'data_saad.csv'
  expert2: 'data_experts2.csv'
  expert3: 'data_experts3.csv'
drop_columns: [
  "e1", "nuc", "free_enegry", "enthalpy_energy"
]
