save_dir: '../../../results/ctf_rth_1.0/'
datasets_dir: '../../../data/predictor/ctf/rth_1.0/'
dataset_params:
  num_folds: 10
  num_bins: 5
  num_bins_hyperparam_opt: 5
models: [
  'knn',
  'xgboost',
  'random_forest',
  'lasso',
  'quantile',
  'bayes',
  'mlp',
  'tabpfn',
  'chemprop'
]
chemprop_params:
  chemprop_model_path: '../training_and_evaluation/foundation_models/chemeleon_mp.pt'
  chemprop_dataset_path: '../../../data/predictor/ctf/data_substrate_ctfs.csv'
metrics: [
  'pairwise_accuracy_score',
  'ndcg_score',
  'rmse',
  'mae',
  'mape',
  'smape',
  'r2_score'
]
hyperparam_opt: True
