remove_threshold: 0.99
feature_generation:
  - types: ['descriptor']
    params:
      descriptor:
        flatness: False
        symmetry: False
  - types: ["ecfp"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
  - types: ["estate"]
    params:
      estate:
        variant: 'sum'
  - types: ['custom_pattern']
    params:
      custom_pattern:
        count: True
  - types: ['maccs']
    params:
      maccs:
        count: True
  - types: ['functional_groups']
    params:
      functional_groups:
        count: True
  - types: [ "ecfp", "estate"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      estate:
        variant: 'sum'
  - types: ['ecfp', 'descriptor']
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      descriptor:
        flatness: False
        symmetry: False
  - types: [ "ecfp", "custom_pattern"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      custom_pattern:
        count: True
  - types: ['ecfp', 'estate', 'descriptor']
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      estate:
        variant: 'sum'
      descriptor:
        flatness: False
        symmetry: False
  - types: ['ecfp', 'estate', 'custom_pattern']
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      estate:
        variant: 'sum'
      custom_pattern:
        count: True
  - types: ['ecfp', 'descriptor', 'custom_pattern']
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      descriptor:
        flatness: False
        symmetry: False
      custom_pattern:
        count: True
  - types: ['ecfp', 'estate', 'descriptor', 'custom_pattern']
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      estate:
        variant: 'sum'
      descriptor:
        flatness: False
        symmetry: False
      custom_pattern:
        count: True
