remove_threshold: 0.99
feature_generation:
  - types: ['descriptor']
    params:
      descriptor: {}
  - types: ['custom_pattern']
    params:
      custom_pattern:
        count: True
  - types: ['descriptor', 'custom_pattern']
    params:
      descriptor: {}
      custom_pattern:
        count: True
  - types: ["ecfp"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
  - types: ["maccs"]
    params:
      maccs:
        count: True
  - types: ["functional_groups"]
    params:
      functional_groups:
        count: True
  - types: ["estate"]
    params:
      estate:
        variant: 'sum'
  - types: ["physiochemical"]
    params:
      physiochemical:
        count: True
        size: 1024
  - types: ["bcut"]
    params:
      bcut: {}
  - types: [ "ecfp", "descriptor"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      descriptor: {}
  - types: [ "maccs", "descriptor"]
    params:
        maccs:
            count: True
        descriptor: {}
  - types: [ "functional_groups", "descriptor"]
    params:
      functional_groups:
        count: True
      descriptor: {}
  - types: [ "ecfp", "descriptor", "custom_pattern" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      descriptor: {}
      custom_pattern:
            count: True
  - types: [ "maccs", "descriptor", "custom_pattern" ]
    params:
      maccs:
        count: True
      descriptor: {}
      custom_pattern:
        count: True
  - types: [ "functional_groups", "descriptor", "custom_pattern" ]
    params:
      functional_groups:
        count: True
      descriptor: {}
      custom_pattern:
        count: True
  - types: [ "ecfp", "bcut" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      bcut: { }
  - types: [ "maccs", "bcut" ]
    params:
      maccs:
        count: True
      bcut: { }
  - types: [ "functional_groups", "bcut" ]
    params:
      functional_groups:
        count: True
      bcut: { }
  - types: [ "ecfp", "estate" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      estate:
        variant: 'sum'
  - types: [ "maccs", "estate" ]
    params:
      maccs:
        count: True
      estate:
        variant: 'sum'
  - types: [ "functional_groups", "estate" ]
    params:
      functional_groups:
        count: True
      estate:
        variant: 'sum'
  - types: [ "ecfp", "physiochemical" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      physiochemical:
        count: True
        size: 1024
  - types: [ "maccs", "physiochemical" ]
    params:
      maccs:
        count: True
      physiochemical:
        count: True
        size: 1024
  - types: [ "functional_groups", "physiochemical" ]
    params:
      functional_groups:
        count: True
      physiochemical:
        count: True
        size: 1024
  - types: [ 'custom_pattern' ]
    params:
      custom_pattern:
        count: False
  - types: [ 'descriptor', 'custom_pattern' ]
    params:
      descriptor: { }
      custom_pattern:
        count: False
  - types: [ "ecfp" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
  - types: [ "maccs" ]
    params:
      maccs:
        count: False
  - types: [ "functional_groups" ]
    params:
      functional_groups:
        count: False
  - types: [ "physiochemical" ]
    params:
      physiochemical:
        count: False
        size: 1024
  - types: [ "ecfp", "descriptor" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      descriptor: { }
  - types: [ "maccs", "descriptor" ]
    params:
      maccs:
        count: False
      descriptor: { }
  - types: [ "functional_groups", "descriptor" ]
    params:
      functional_groups:
        count: False
      descriptor: { }
  - types: [ "ecfp", "descriptor", "custom_pattern" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      descriptor: { }
      custom_pattern:
        count: False
  - types: [ "maccs", "descriptor", "custom_pattern" ]
    params:
      maccs:
        count: False
      descriptor: { }
      custom_pattern:
        count: False
  - types: [ "functional_groups", "descriptor", "custom_pattern" ]
    params:
      functional_groups:
        count: False
      descriptor: { }
      custom_pattern:
        count: False
  - types: [ "ecfp", "bcut" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      bcut: { }
  - types: [ "maccs", "bcut" ]
    params:
      maccs:
        count: False
      bcut: { }
  - types: [ "functional_groups", "bcut" ]
    params:
      functional_groups:
        count: False
      bcut: { }
  - types: [ "ecfp", "estate" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      estate:
        variant: 'sum'
  - types: [ "maccs", "estate" ]
    params:
      maccs:
        count: False
      estate:
        variant: 'sum'
  - types: [ "functional_groups", "estate" ]
    params:
      functional_groups:
        count: False
      estate:
        variant: 'sum'
  - types: [ "ecfp", "physiochemical" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      physiochemical:
        count: False
        size: 1024
  - types: [ "maccs", "physiochemical" ]
    params:
      maccs:
        count: False
      physiochemical:
        count: False
        size: 1024
  - types: [ "functional_groups", "physiochemical" ]
    params:
      functional_groups:
        count: False
      physiochemical:
        count: False
        size: 1024
  - types: ["ecfp", "physiochemical", "descriptor"]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: True
      physiochemical:
        count: True
        size: 1024
      descriptor: {}
  - types: [ "ecfp", "physiochemical", "descriptor" ]
    params:
      ecfp:
        radius: 2
        size: 1024
        count: False
      physiochemical:
        count: False
        size: 1024
      descriptor: { }
