repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
        exclude: '^(configs/reinvent/templates/).*'
      - id: check-yaml
        files: '^(?!tests//).*(\.yaml)$'

  - repo: https://github.com/crate-ci/typos
    rev: v1.43.3
    hooks:
      - id: typos
        exclude: '^(notebooks/|modules/predictor/notebooks/|configs/).*'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
        args: [ "--config=pyproject.toml", "-rrs=False" ]

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: .venv/bin/ty check
        language: system
        types: [ python ]
        pass_filenames: false
