[project]
name = "battery-rangers"
version = "0.1.0"
description = "A repository for molecule machine learning for batteries."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepchem>=2.8.0",
    "jupyter>=1.1.1",
    "networkx>=3.4.2",
    "numpy>=2.2.2",
    "pre-commit>=4.1.0",
    "pylint>=3.3.3",
    "pymatgen>=2025.1.23",
    "pyscf>=2.8.0",
    "pytest>=8.3.4",
    "scikit-learn>=1.6.1",
    "scikit-optimize>=0.10.2",
    "vtk>=9.4.1",
    "xgboost>=2.1.3",
]
