# REINVENT4 TOML input example for reinforcement/curriculum learning
#
# Curriculum learning in REINVENT4 is a multi-stage reinforcement learning
# run. One or more stages (auto CL) can be defined. But it is also
# possible to continue a run from any checkpoint file that is generated
# during the run (manual CL). Currently, checkpoints are written at the end
# of a run also when the run is forcefully terminated with Ctrl-C.


# NODE
run_type = "staged_learning"
device = "cuda:0"  # set torch device e.g. "cpu"
tb_logdir = "outputs/tensorboard"  # name of the TensorBoard logging directory
seed = 23

[parameters]

summary_csv_prefix = "staged_learning_node_chembl35_ft_rl_no_inception"  # prefix for the CSV file
use_checkpoint = false  # if true read diversity filter from agent_file
purge_memories = true  # if true purge all diversity filter memories after each stage

# vanilla + rl
#prior_file = "models/reinvent/reinvent.prior"
#agent_file = "models/reinvent/reinvent.prior"

# vanilla + fine-tuned + rl
# prior_file = "models/reinvent/node/vanilla_ft.model"
# agent_file = "models/reinvent/node/vanilla_ft.model"

# chembl_35 + rl
# prior_file = "models/reinvent/pretrained_chembl_35.model"
# agent_file = "models/reinvent/pretrained_chembl_35.model"

# chembl_35 + fine-tuned + rl
 prior_file = "models/reinvent/node/chembl_35_fine_tuned.model"
 agent_file = "models/reinvent/node/chembl_35_fine_tuned.model"

batch_size = 256 # network

unique_sequences = true  # if true remove all duplicates raw sequences in each step
# only here for backward compatibility
randomize_smiles = true  # if true shuffle atoms in SMILES randomly


[learning_strategy]

type = "dap"      # dap: only one supported
sigma = 256       # sigma of the RL reward function
rate = 0.00005    # for torch.optim


[diversity_filter]  # optional, comment section out or remove if unneeded
# NOTE: also memorizes all seen SMILES

type = "PenalizeSameSmiles" # IdenticalTopologicalScaffold,
# ScaffoldSimilarity, PenalizeSameSmiles
bucket_size = 25                 # memory size in number of compounds
minscore = 0.4                   # only memorize if this threshold is exceeded
minsimilarity = 0.4              # minimum similarity for ScaffoldSimilarity
penalty_multiplier = 0.5         # penalty factor for PenalizeSameSmiles


# Reinvent only: guide RL in the initial phase
#[inception]  # optional, comment sectionout or remove if unneeded
#smiles_file = "data/raw/node/train_node.smi"  # "good" SMILES for guidance
#memory_size = 100  # number of total SMILES held in memory
#sample_size = 10  # number of SMILES randomly chosen each epoch


### Stage 1
### Note that stages must always be a list i.e. double brackets
[[stage]]

chkpt_file = 'models/reinvent/node/chembl_35_pretrained_ft_rl_no_inception_fixed.model'

termination = "simple"  # termination criterion fot this stage
max_score = 1.0  # terminate if this total score is exceeded
min_steps = 50  # run for at least this number of steps
max_steps = 200  # terminate entire run when exceeded

[stage.scoring]
type = "geometric_mean"  # aggregation function

[[stage.scoring.component]]
[stage.scoring.component.BatteryPropertiesNode]

[[stage.scoring.component.BatteryPropertiesNode.endpoint]]
known_smiles_path = "data/raw/node/train_node.smi"  # path to known SMILES file
