#    num_envs: Increases the diversity of experiences collected in parallel.
#    n_steps: Increases the length of each experience chunk,
#       which is crucial for the agent to learn the long-term consequences of its actions (improves credit assignment).
#    epoch: Increases the number of times the agent learns from each batch of experience.
#       Since this happens on the GPU, it's computationally "cheaper" than collecting more data.

# RUN WITH:
# python scripts/mol_air_wrapper.py <path to config file> --init_selfies_path <path to .slf file with seed molecules>
# --init_selfies_path is optional

# TODO: pick experiment name
#Mol-AIR-vanilla-rl-seed-molecules-new-reward:
 Mol-AIR-vanilla-rl-new-reward:
  Agent:
    type: RND
    n_steps: 64
    epoch: 3
    seq_len: 35
    seq_mini_batch_size: 256
    gamma: 0.99
    nonepi_adv_coef: 1.0
    entropy_coef: 0.001
  CountIntReward:
    crwd_coef: 0.1 # increase to improve exploration
  Train:
    num_envs: 8
    seed: 2137
    total_time_steps: 250000
    summary_freq: 2500
    agent_save_freq: 12500
    num_inference_envs: 8
    n_inference_episodes: 1000 # Consider increasing this later for better validation
    lr: 1.0e-4
    grad_clip_max_norm: 5.0
    device: cuda
    pretrained_path: models/mol_air/vanilla/pretrained.pt
  Inference:
    num_envs: 2
    n_episodes: 10000
    device: cuda
    ckpt: best
  Env:
    custom_property_coef: 1.0
    max_str_len: 35
    vocab_path: models/mol_air/vanilla/vocab.json
