# REINVENT4 TOML input example for transfer learning
#
# Focus a given model towards a set of input SMILES.  This can also be used to
# start from scratch from and an untrained prior.


run_type = "transfer_learning"
device = "cuda:0"  # set torch device e.g. "cpu"
tb_logdir = "tb_TL"  # name of the TensorBoard logging directory
seed =  23
[parameters]
num_epochs = 50  # number of steps to run
save_every_n_epochs = 10  # save checkpoint model file very N steps
batch_size = 4096
num_refs = 0  # number of reference molecules randomly chosen for similarity set this to zero for large datasets (>200 molecules)!
sample_batch_size = 4096  # number of sampled molecules to compute sample loss

randomize_smiles = false
standardize_smiles = false

clip_gradient_norm = 1.0

## Reinvent
#input_model_file = "modules/REINVENT4/priors/reinvent.prior"
input_model_file = "models/reinvent/reinvent_empty_model_discovered_smarts.model"
output_model_file = "models/reinvent/reinvent_discovered_smarts_pretrained.model"

smiles_file = "data/discovered/substrate_discovered_smarts_train.smi"
validation_smiles_file = "data/discovered/substrate_discovered_smarts_test.smi"

[scheduler]
lr = 0.001                           # Standard starting learning rate for Adam
step = 20                            # Decay LR every 20 epochs
gamma = 0.8                          # Multiply LR by 0.8 at every step
min = 0.00001                        # Stop training if LR falls below this
