# TOML input configuration to create a new empty model
#
# Empty model means that a SMILES file is scanned for all possible tokens
# to determine the vocabulary and to set the model's hyper-parameters. A
# separate TL step is needed to actually train the prior on the same
# dataset.

# run this with
# modules/REINVENT4/reinvent/runmodes/create_model/create_reinvent.py
[io]
smiles_file = "data/chembl_35_sqlite/chembl_35.smi" # created using modules/REINVENT4/reinvent/datapipeline/preprocess.py and preprocess.toml config
model_file = "outputs/reinvent_empty_model_chembl_35.model"


[network]  # hyper-parameters
num_layers = 3
layer_size = 512
dropout = 0.0
layer_normalization = false
standardize = false  # should be true to ensure data consistency, should be false for new prior training from scratch


[metadata]  # metadata for the model, information about the data source
data_source = "ChEMBL 35"
comment = "This is a test"
