# REINVENT4 TOML input example for sampling
run_type = "sampling"
device = "cuda"
seed = 23

[parameters]

# vanilla + RL
#model_file = "outputs/staged_learning/vanilla_rl.chkpt"
#output_file = 'data/sampling/reinvent/vanilla_rl.csv'

# vanilla
#model_file = "modules/REINVENT4/priors/reinvent.prior"
#output_file = "data/sampling/reinvent/vanilla.csv"

# vanilla + ft
#model_file = "outputs/transfer_learning/vanilla_finetuned.model"
#output_file = "data/sampling/reinvent/vanilla_finetuned.csv"

# vanill + ft + RL
#model_file = "outputs/staged_learning/vanilla_finetuned_rl.chkpt"
#output_file = "data/sampling/reinvent/vanilla_finetuned_rl.csv"

# chembl35 pretrained
#model_file = "outputs/transfer_learning/200_epochs/pretrained_chembl_35.model"
#output_file = "data/sampling/reinvent/pretrained_chembl_35.csv"

# chembl35 pretrained + ft
#model_file = "outputs/transfer_learning/200_epochs/chembl_35_fine_tuned.model"
#output_file = "data/sampling/reinvent/finetuned_chembl_35.csv"

# chembl35 pretrained + ft + RL
model_file = "outputs/staged_learning/chembl_finetuned_rl_with_inception.chkpt"
output_file = "data/sampling/reinvent/finetuned_chembl_35_rl.csv"


num_smiles = 10000  # number of SMILES to be sampled, 1 per input SMILES
unique_molecules = false  # if true remove all duplicatesd canonicalize smiles
randomize_smiles = false # if true shuffle atoms in SMILES randomly
