# This workflow will install and run pylint.

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          # This is a list of components to remove.
          # You can customize it if you need to keep some tools.
          # The default list is usually sufficient.
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          # This action also clears the Docker cache by default
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t test-dockerfile -f test.Dockerfile .

#      - name: Set up python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.12.6"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pylint
#      - name: Lint with pylint
#        run: |
#          export PYTHONPATH=$PYTHONPATH:/home/runner/work/battery-rangers/battery-rangers
#          pylint modules --rcfile=/home/runner/work/battery-rangers/battery-rangers/.pylintrc --disable=import-error
